"""Add a listed company to Folio: find its latest annual report, verify it, index it.

Ingest step (SPEC.md §4). One offline command:

    python -m ingest.add UNIHEALTH            # one company
    python -m ingest.add UNIHEALTH HCC        # batch: several, one after another
    python -m ingest.add --all                # every company in corpus/urls.yaml
    python -m ingest.add HCC --verify         # re-download and check the checksum, change nothing

For each company it (1) collects candidate reports from corpus/urls.yaml:
explicit URLs maintained by hand, then the PDFs linked from the company's
investor page; (2) works out each candidate's fiscal year, from the link text
where the page says it and from the report's own first pages where it does
not; (3) picks the latest; (4) downloads it, refusing a scanned report;
(5) records its URL and SHA-256 in corpus.json and corpus/SOURCES.md; and
(6) runs the v1.1 pipeline (extract, preprocess, tables, chunk, embed) on
that filing alone, replacing only that company's rows in the index.

Idempotent: a company whose latest report is already indexed, from the same
source with the same checksum, is reported as up to date and nothing on disk
changes. Why the sources are what they are is in ingest/fetch.py.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import time
from pathlib import Path

import fitz
import yaml

from ingest.build import ingest_filing
from ingest.fetch import Refused, download, fiscal_year_of, fiscal_years_in, get, pdf_links
from retrieve.embed import embed_texts, load_model, replace_filing, to_arrow

URLS = Path("corpus/urls.yaml")
MANIFEST = Path("corpus/corpus.json")
SOURCES = Path("corpus/SOURCES.md")
CORPUS = Path("corpus")
DATA = Path("data")
DB = Path("data/lancedb")
# Fiscal years already read from a downloaded report, by URL, so a second run
# does not download last year's report again just to learn which year it is.
SEEN = Path("data/seen_reports.json")

# A page with no extractable text at all is a picture: a cover, a photo, a
# scanned letter. A real annual report has a few (HCC 4 of 296). Past this
# share the report is a scan, and there is no OCR path (SPEC.md §3.5).
MAX_TEXTLESS_SHARE = 0.20

GENERATED = ("<!-- generated by ingest.add from corpus.json: edit corpus/urls.yaml, not this table -->",
             "<!-- end generated -->")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def textless_pages(pdf: Path) -> tuple[list[int], int]:
    """Viewer page numbers with no text layer, and the page count."""
    with fitz.open(pdf) as doc:
        return [i + 1 for i, page in enumerate(doc) if not page.get_text().strip()], len(doc)


def check_born_digital(pdf: Path) -> list[int]:
    """Return the pages to skip, or raise Refused if the report is a scan."""
    missing, total = textless_pages(pdf)
    if missing:
        print(f"    {len(missing)} of {total} pages have no text layer and are skipped: {missing}")
    if len(missing) > MAX_TEXTLESS_SHARE * total:
        raise Refused(f"{len(missing)} of {total} pages have no text layer ({len(missing) / total:.0%}); "
                      "this looks scanned, and Folio has no OCR path (SPEC.md §3.5)")
    return missing


def candidates(company: str, config: dict, seen: dict, manifest: list[dict]) -> list[dict]:
    """Every report this company's sources point to, each with its fiscal year if known yet.

    Explicit URLs come first, so on a tie for the latest year the hand-kept
    link wins over one scraped from a page.
    """
    known = {entry["source_url"]: entry["fiscal_year"] for entry in manifest}
    found = [{"url": r["url"], "fiscal_year": r.get("fiscal_year"), "how": "urls.yaml"} for r in config.get("reports", [])]
    if config.get("investor_page"):
        page = config["investor_page"]
        try:
            html = get(page).decode("utf-8", errors="replace")
        except Refused as error:
            print(f"    investor page unavailable ({error}); using urls.yaml only")
            html = ""
        for url, label in pdf_links(page, html):
            years = fiscal_years_in(label)
            found.append({"url": url, "fiscal_year": max(years) if len(years) == 1 else None,
                          "how": f"investor page, link “{label[:60]}”"})
    for c in found:
        c["fiscal_year"] = c["fiscal_year"] or known.get(c["url"]) or seen.get(c["url"], {}).get("fiscal_year")
    return found


def resolve_years(found: list[dict], seen: dict) -> None:
    """Read the fiscal year of unlabelled candidates from the reports themselves, a few at most."""
    from ingest.fetch import MAX_UNLABELLED_DOWNLOADS

    unknown = [c for c in found if not c["fiscal_year"]][:MAX_UNLABELLED_DOWNLOADS]
    for c in unknown:
        path = DATA / "downloads" / (hashlib.sha1(c["url"].encode()).hexdigest()[:16] + ".pdf")
        try:
            download(c["url"], path)
        except Refused as error:
            print(f"    skipped {c['url']}: {error}")
            continue
        c["fiscal_year"], c["path"] = fiscal_year_of(path), path
        seen[c["url"]] = {"fiscal_year": c["fiscal_year"]}


def fy_number(label: str | None) -> int:
    return int(label[2:]) if label else -1


def add_company(company: str, config: dict, manifest: list[dict], seen: dict, model, verify: bool,
                force: bool = False) -> str:
    """Bring one company up to date. Returns what happened, in a few words."""
    print(f"\n{company} — {config['name']}")
    existing = next((e for e in manifest if e["company"] == company), None)

    if verify:
        if not existing:
            return "not indexed, nothing to verify"
        path = DATA / "downloads" / "verify.pdf"
        download(existing["source_url"], path)
        digest = sha256(path)
        ok = digest == existing["sha256"]
        print(f"    re-downloaded {existing['source_url']}\n    sha256 {digest}\n    "
              f"{'matches' if ok else 'DOES NOT match'} the recorded {existing['sha256']}")
        return "checksum matches" if ok else "checksum MISMATCH"

    found = candidates(company, config, seen, manifest)
    resolve_years(found, seen)
    dated = [c for c in found if c["fiscal_year"]]
    if not dated:
        return "no annual report found"
    latest = max(dated, key=lambda c: fy_number(c["fiscal_year"]))  # max() keeps the first on a tie
    fy = latest["fiscal_year"]
    print(f"    latest: {fy} from {latest['how']}\n    {latest['url']}")

    if existing and fy_number(existing["fiscal_year"]) >= fy_number(fy) and not force:
        on_disk = CORPUS / existing["file"]
        if on_disk.exists() and sha256(on_disk) == existing["sha256"]:
            return f"up to date ({existing['fiscal_year']} already indexed)"

    file_name = existing["file"] if existing and existing["source_url"] == latest["url"] else f"{company.lower()}_{fy.lower()}.pdf"
    target = CORPUS / file_name
    if force and existing and existing["source_url"] == latest["url"] and target.exists() \
            and sha256(target) == existing["sha256"]:
        # Re-indexing after a pipeline change needs the file, not a new copy.
        pass
    elif latest.get("path"):
        shutil.copyfile(latest["path"], target)
    else:
        download(latest["url"], target)
    detected = fiscal_year_of(target)
    if detected and detected != fy:
        print(f"    note: the report's own pages say {detected}; using {fy} from {latest['how']}")
    skipped = check_born_digital(target)

    entry = {"file": file_name, "company": company, "name": config["name"], "fiscal_year": fy,
             "source_url": latest["url"], "sha256": sha256(target), "listing": config.get("listing", ""),
             "pages_without_text": skipped, "retrieved": time.strftime("%Y-%m-%d")}
    started = time.perf_counter()
    chunk_path = ingest_filing(entry, CORPUS, DATA)
    chunks = [json.loads(line) for line in chunk_path.read_text(encoding="utf-8").splitlines()]
    replace_filing(to_arrow(chunks, embed_texts(model, [c["text"] for c in chunks])), company, DB)
    print(f"    indexed {len(chunks)} chunks in {time.perf_counter() - started:.0f}s")

    if existing:
        manifest[manifest.index(existing)] = entry
    else:
        manifest.append(entry)
    if not existing:
        return f"added {fy}"
    return f"re-indexed {fy}" if existing["fiscal_year"] == fy else f"replaced {existing['fiscal_year']} with {fy}"


def write_sources(manifest: list[dict]) -> None:
    """Regenerate the filings table in SOURCES.md from corpus.json; the prose around it is kept."""
    rows = ["| Company | Listing | Fiscal year | Filename | SHA-256 | Source |", "|---|---|---|---|---|---|"]
    for e in manifest:
        rows.append(f"| {e['name']} ({e['company']}) | {e.get('listing', '')} | {e['fiscal_year']} | "
                    f"`{e['file']}` | `{e['sha256']}` | <{e['source_url']}> |")
    text = SOURCES.read_text(encoding="utf-8")
    start, end = text.index(GENERATED[0]), text.index(GENERATED[1])
    save_if_changed(SOURCES, text[:start] + GENERATED[0] + "\n" + "\n".join(rows) + "\n" + text[end:])


def save_if_changed(path: Path, text: str) -> None:
    """Write only on a real change, so an up-to-date run leaves every file untouched."""
    if not path.exists() or path.read_text(encoding="utf-8") != text:
        path.write_text(text, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Add listed companies' latest annual reports to the index.")
    parser.add_argument("companies", nargs="*", help="company codes from corpus/urls.yaml, e.g. UNIHEALTH HCC")
    parser.add_argument("--all", action="store_true", help="every company in corpus/urls.yaml")
    parser.add_argument("--verify", action="store_true", help="re-download each indexed report and compare its SHA-256")
    parser.add_argument("--force", action="store_true",
                        help="re-index even if up to date, after a change to the pipeline itself")
    args = parser.parse_args()

    config = yaml.safe_load(URLS.read_text(encoding="utf-8"))
    companies = list(config) if args.all else [c.upper() for c in args.companies]
    unknown = [c for c in companies if c not in config]
    if unknown or not companies:
        raise SystemExit(f"not in {URLS}: {unknown}" if unknown else "name at least one company, or --all")

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    seen = json.loads(SEEN.read_text(encoding="utf-8")) if SEEN.exists() else {}
    model = None if args.verify else load_model()
    results = {}
    for company in companies:
        try:
            results[company] = add_company(company, config[company], manifest, seen, model, args.verify, args.force)
        except Refused as error:
            results[company] = f"refused: {error}"

    if not args.verify:
        save_if_changed(MANIFEST, json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
        SEEN.parent.mkdir(exist_ok=True)
        save_if_changed(SEEN, json.dumps(seen, indent=1, sort_keys=True) + "\n")
        write_sources(manifest)
    print("\n" + "\n".join(f"  {c}: {r}" for c, r in results.items()))


if __name__ == "__main__":
    main()
